baseURL = "https://www.softwarestartupacademy.com"
relativeURLs = true
languageCode = "en-us"
title = "Training For Tech Entrepreneurs and Software Startups"


theme = "agency-theme"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = false
defaultContentLanguage = "en"

[taxonomies]
  category = "categories"
  contributor = "contributors"
  tag = "tags"

[permalinks]
    blog = "/:title"
    categories = "/:title"
    landingpages = "/:title"
    mainpages = "/:title"


[params]
    contentDir = "content"
    weight = 10
    languageCode = "en-us"
    title = "Training For Tech Entrepreneurs and Software Startups"
    dateFormat = "January 2, 2006"

    logo = "img/logos/software-startup-academy-logo.png"
    menufixed = false