[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.83.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"


[[redirects]]
from = "https://app.softwarestartupacademy.com/*"
to = "https://members.topbusinesscoaching.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://app.softwarestartupacademy.com"
to = "https://app.softwarestartupacademy.com"
status = 301
force = true

